[[domains]]
domain_name = "3dprintbeast.com"
subdomains = ["www"]
include_base_domain = false

[[domains]]
domain_name = "accountinginsights.org"

[[domains]]
domain_name = "audiochamps.com"

[[domains]]
domain_name = "amycookseats.com"

[[domains]]
domain_name = "codezup.com"

[[domains]]
domain_name = "cookingupdate.com"

[[domains]]
domain_name = "devcodef1.com"

[[domains]]
domain_name = "easytechsolver.com"

[[domains]]
domain_name = "eatinghealthyplan.com"

[[domains]]
domain_name = "economatik.com"

[[domains]]
domain_name = "gbtimes.com"

[[domains]]
domain_name = "glossykitchen.com"

[[domains]]
domain_name = "homediningkitchen.com"

[[domains]]
domain_name = "ittrip.xyz"
subdomains = ["*"]

[[domains]]
domain_name = "kitchensnitches.com"

[[domains]]
domain_name = "onexception.dev"

[[domains]]
domain_name = "ricearray.org"
subdomains = ["www"]
include_base_domain = false

[[domains]]
domain_name = "shecodes.io"
subdomains = ["www"]
paths = ["athena/*"]
include_base_domain = false

[[domains]]
domain_name = "shungrill.com"

[[domains]]
domain_name = "slingacademy.com"
subdomains = ["www"]
include_base_domain = false

[[domains]]
domain_name = "studygyaan.com"

[[domains]]
domain_name = "khueapps.com"
subdomains = ["www"]
include_base_domain = false

[[domains]]
domain_name = "tecadmin.net"

[[domains]]
domain_name = "techrebooter.com"

[[domains]]
domain_name = "thekitchentoday.com"

[[domains]]
domain_name = "thetechylife.com"

[[domains]]
domain_name = "trycatchdebug.net"

[[domains]]
domain_name = "umatechnology.org"

[[domains]]
domain_name = "webdevtutor.net"
subdomains = ["www"]
include_base_domain = false
